export const NORMAL_TITLE = 'Normal';

export const CNV_TITLE = 'Choroidal neovascularization';
export const CNV_INFO = 'Choroidal neovascularization (CNV) is the creation of new blood vessels in the choroid layer of the eye. Choroidal neovascularization is a common cause of neovascular degenerative maculopathy (i.e. \'wet\' macular degeneration) commonly exacerbated by extreme myopia, malignant myopic degeneration, or age-related developments.';
export const CNV_TREATMENT = 'CNV is conventionally treated with intravitreal injections of angiogenesis inhibitors (also known as "anti-VEGF" drugs) to control neovascularization and reduce the area of fluid below the retinal pigment epithelium. Angiogenesis inhibitors include pegaptanib, ranibizumab and bevacizumab (known by a variety of trade names, such as Macugen, Avastin or Lucentis). These inhibitors slow or stop the formation of new blood vessels (angiogenesis), typically by binding to or deactivating the transmission of vascular endothelial growth factor (\'VEGF\'), a signal protein produced by cells to stimulate formation of new blood vessels. The effectiveness of angiogenesis inhibitors has been shown to significantly improve visual prognosis with CNV, the recurrence rate for these neovascular areas remains high. CNV may also be treated with photodynamic therapy coupled with a photosensitive drug such as verteporfin (Visudyne). The drug is given intravenously. It is then activated in the eye by a laser light. The drug destroys the new blood vessels, and prevents any new vessels forming by forming thrombi.';

export const DME_TITLE = 'Diabetic macular edema';
export const DME_INFO = 'Macular edema occurs when fluid and protein deposits collect on or under the macula of the eye (a yellow central area of the retina) and causes it to thicken and swell (edema). The swelling may distort a person\'s central vision, because the macula holds tightly packed cones that provide sharp, clear, central vision to enable a person to see detail, form, and color that is directly in the centre of the field of view. Diabetic macular edema (DME) is similarly caused by leaking macular capillaries. DME is the most common cause of visual loss in both proliferative, and non-proliferative diabetic retinopathy.';
export const DME_TREATMENT = 'Macular edema sometimes occurs for a few days or weeks after cataract surgery, but most such cases can be successfully treated with NSAID or cortisone eye drops. Prophylactic use of Nonsteroidal anti-inflammatory drugs has been reported to reduce the risk of macular edema to some extent. In 2010, the US FDA approved the use of Lucentis intravitreal injections for macular edema. Iluvien, a sustained release intravitreal implant developed by Alimera Sciences, has been approved in Austria, Portugal and the U.K. for the treatment of vision impairment associated with chronic diabetic macular edema (DME) considered insufficiently responsive to available therapies. Additional EU country approvals are anticipated. In 2013 Lucentis by intravitreal injection was approved by the National Institute for Health and Care Excellence in the UK for the treatment of macular edema caused by diabetes and/or retinal vein occlusion. On July 29, 2014, Eylea (aflibercept), an intravitreal injection produced by Regeneron Pharmaceuticals Inc., was approved to treat DME in the United States.';

export const DRUSEN_TITLE = 'Drusen';
export const DRUSEN_INFO = 'Drusen, from the German word for node or geode (singular, "Druse"), are tiny yellow or white accumulations of extracellular material that build up between Bruch\'s membrane and the retinal pigment epithelium of the eye. The presence of a few small ("hard") drusen is normal with advancing age, and most people over 40 have some hard drusen. However, the presence of larger and more numerous drusen in the macula is a common early sign of age-related macular degeneration (AMD).';
export const DRUSEN_TREATMENT = 'Laser treatment of drusen has been studied. While it is possible to eliminate drusen with this treatment strategy, it has been shown that this fails to reduce the risk of developing the choroidal neovascularisation which causes the blindness associated with age-related macular degeneration.';

export const CSR_TITLE = 'Central serous retinopathy';
export const CSR_INFO = 'Central serous retinopathy (CSR), also known as central serous chorioretinopathy (CSC or CSCR), is an eye disease that causes visual impairment, often temporary, usually in one eye. When the disorder is active it is characterized by leakage of fluid under the retina that has a propensity to accumulate under the central macula. This results in blurred or distorted vision (metamorphopsia). A blurred or gray spot in the central visual field is common when the retina is detached. Reduced visual acuity may persist after the fluid has disappeared.';
export const CSR_TREATMENT = 'Most eyes with CSR undergo spontaneous resorption of subretinal fluid within 3–4 months. Recovery of visual acuity usually follows. Treatment should be considered if resorption does not occur within 3–4 months, spontaneously or as the result of counselling. Any ongoing corticosteroid treatment should be tapered and stopped, where possible. It is important to check current medication, including nasal sprays and creams, for ingredients of corticosteroids, if found seek advice from a medical practitioner for an alternative.';

export const MH_TITLE = 'Macular hole';
export const MH_INFO = 'A macular hole is a small break in the macula, located in the center of the eye\'s light-sensitive tissue called the retina.';
export const MH_TREATMENT = 'Vitrectomy is the common way to treat a macular hole. It is done by placing a gas bubble in the vitreous of the eye which helps flatten the macular hole and holds it in place as the eye heals. The gas bubble slowly shrinks on its own. Treatment is also done using ocriplasmin.';